version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redispass
      - REDIS_DATABASES=16
    command: ["redis-server", "--requirepass", "redispass", "--databases", "16"]
